package org.trackerd.platform.clouddocker.builder.tomcat;

import java.io.*;
import java.net.*;
import java.nio.charset.*;

import javax.xml.stream.*;

import org.apache.commons.compress.archivers.*;
import org.apache.commons.compress.archivers.tar.*;
import org.trackerd.platform.clouddocker.config.*;
import org.trackerd.platform.clouddocker.docker.*;

public class TomcatBuilder
{
	public static String build(TomcatBuilderConfig builderConfig) throws Exception
	{
		String tempDirPath= System.getProperty("java.io.tmpdir")+"builder-tomcat-"+System.nanoTime();
		System.out.println("Created temp dir: "+ tempDirPath);
		File tempDir= new File(tempDirPath);
		tempDir.mkdir();

		File indexFile= new File(org.trackerd.platform.clouddocker.builder.tomcat.TomcatBuilder.class.getResource("index.html").getFile());
		copy(indexFile, new File(tempDirPath+"/index.html"));

		File tomcatUsersFile= new File(org.trackerd.platform.clouddocker.builder.tomcat.TomcatBuilder.class.getResource("tomcat-users.xml").getFile());
		copyAndAdjustTomcatUsersFile(tomcatUsersFile, tempDirPath, builderConfig);

		createDockerFile(tempDirPath, builderConfig);

		downloadWarFiles(tempDirPath, builderConfig.warFiles);

		File tarFile= createTarFile(tempDirPath, builderConfig.warFiles);

		String tagName= builderConfig.tag != null ? builderConfig.tag : "tomcat/"+System.currentTimeMillis();
		DockerWrapper.build(tarFile, tagName);

		cleanupTempDir(tempDir);

		return tagName;
	}

	private static File createTarFile(String tempDirPath, String warFiles[]) throws Exception
	{
		File tarFile= new File(tempDirPath+"/docker.tar");
		OutputStream tarOutput= new FileOutputStream(tarFile);

		ArchiveOutputStream archiveOutput= new ArchiveStreamFactory().createArchiveOutputStream(ArchiveStreamFactory.TAR, tarOutput);

		archiveFile(tempDirPath, "Dockerfile", archiveOutput);
		archiveFile(tempDirPath, "index.html", archiveOutput);
		archiveFile(tempDirPath, "tomcat-users.xml", archiveOutput);

		for(String warFile : warFiles)
			archiveFile(tempDirPath, warFile, archiveOutput);

		archiveOutput.finish(); 
        tarOutput.close();
        
		return tarFile;
	}

	private static void archiveFile(String tempDirPath, String filename, ArchiveOutputStream archiveOutput) throws IOException
	{
		File originalFile= new File(tempDirPath + '/' + filename);
		File tarInputFile= new File(filename);
		TarArchiveEntry tarFile= new TarArchiveEntry(tarInputFile);
		tarFile.setSize(originalFile.length());
		archiveOutput.putArchiveEntry(tarFile);
		copy(originalFile, archiveOutput);
		archiveOutput.closeArchiveEntry();
	}

	private static void createDockerFile(String tempDirPath, TomcatBuilderConfig builderConfig) throws IOException
	{
		BufferedWriter writer= new BufferedWriter(new FileWriter(new File(tempDirPath+"/Dockerfile")));

		writer.write("FROM marcel/"+Config.accessor().getBaseImage()+'\n');
		writer.write("MAINTAINER Generated by CloudDocker\n");
		writer.write("ADD index.html /var/lib/tomcat7/webapps/ROOT/\n");
		writer.write("ADD tomcat-users.xml /etc/tomcat7/\n");
		for(String warFile: builderConfig.warFiles)
			writer.write("ADD "+warFile+" /var/lib/tomcat7/webapps/\n");			
		writer.write("CMD service tomcat7 start && tail -F /var/lib/tomcat7/logs/catalina.out\n");
		
		writer.flush();
		writer.close();
	}

	private static void copyAndAdjustTomcatUsersFile(File tomcatUsersFile, String tempDirPath, TomcatBuilderConfig builderConfig) throws IOException
	{
		BufferedReader reader= new BufferedReader(new InputStreamReader(new FileInputStream(tomcatUsersFile), Charset.forName("UTF-8")));
		BufferedWriter writer= new BufferedWriter(new FileWriter(new File(tempDirPath+"/tomcat-users.xml")));
		String line= null;
		while ((line= reader.readLine()) != null)
		{
			line= line.replace("##username", builderConfig.username);
			line= line.replace("##password", builderConfig.password);
			
			writer.write(line+'\n');
		}
		
		writer.flush();
		writer.close();
		reader.close();
	}

	private static void downloadWarFiles(String tempDirPath, String[] warFiles)
	{
		for(String warFile: warFiles)
			execGetSaveFile('/'+warFile, tempDirPath+'/'+warFile);

	}

	private static void execGetSaveFile(String command, String path)
	{
		try
		{
		    URL dockerURL= new URL(Config.accessor().getUrlForWarLocation()+command);
			HttpURLConnection connection= (HttpURLConnection)dockerURL.openConnection();
	        
	        connection.setRequestMethod("GET");
	        connection.setReadTimeout(10000);

	        connection.connect();
	        
	        copy(connection.getInputStream(), new File(path));

	        connection.disconnect();

		} catch(MalformedURLException e)
		{
			e.printStackTrace();
		} catch(IOException e)
		{
			e.printStackTrace();
		} catch(FactoryConfigurationError e)
		{
			e.printStackTrace();
		}
	}

	
	public static void copy(File src, File dst) throws IOException
	{
		InputStream in= new FileInputStream(src);
		OutputStream out= new FileOutputStream(dst);

		byte[] buf= new byte[1024];
		int len;
		while ((len= in.read(buf)) > 0)
		{
			out.write(buf, 0, len);
		}
		in.close();
		out.close();
	}

	public static void copy(InputStream in, File dst) throws IOException
	{
		OutputStream out= new FileOutputStream(dst);

		byte[] buf= new byte[1024];
		int len;
		while ((len= in.read(buf)) > 0)
		{
			out.write(buf, 0, len);
		}
		in.close();
		out.close();
	}

	public static void copy(File src, ArchiveOutputStream out) throws IOException
	{
		InputStream in= new FileInputStream(src);

		byte[] buf= new byte[1024];
		int len;
		while ((len= in.read(buf)) > 0)
		{
			out.write(buf, 0, len);
		}
		in.close();
	}


	private static void cleanupTempDir(File tempDir)
	{
		String[] files= tempDir.list();
		for(String file: files)
			new File(tempDir.getPath()+'/'+file).delete();
		tempDir.delete();
	}


}
